### ISSUE TITLE
Readme links are broken

### ISSUE THREAD

**Issue by jasonrberk** [goldmansachs/gs-collections-kata#9]
as stated

**Comment by jasonrberk** [comment]
<img width="1039" alt="Screen Shot 2021-01-18 at 5 17 36 PM" src="https://user-images.githubusercontent.com/31823413/104967320-14530280-59b1-11eb-8879-992775131112.png">

first off, the link aren't rendered correctly.  I think you could wrap them in `<` and `>` to deal with the spaces.  Seemed to work in my fork, but I stopped because the links appear broken and just send you to `https://github.com/eclipse/eclipse-collections`

**Comment by nikhilnanivadekar** [comment]
GS Collections has moved to Eclipse Collections. Below are the details:
Website: eclipse.org/collections
Repo: github.com/eclipse/eclipse-collections 
Kata: https://github.com/eclipse/eclipse-collections-kata
